# Generated by Django 4.0.6 on 2022-08-10 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_dislikes_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Общий рейтинг'),
        ),
        migrations.AddField(
            model_name='project',
            name='dislikes_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='project',
            name='likes_dislikes_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Общий рейтинг'),
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vote', models.SmallIntegerField(choices=[(-1, 'Не нравится'), (1, 'Нравится')], verbose_name='Голос')),
                ('object_id', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_likes', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
