# Generated by Django 4.0.6 on 2022-08-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment_dislikes_count_comment_likes_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='likedislike',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likes_dislikes_count',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='likes_dislikes_count',
            new_name='rating',
        ),
    ]
