# Generated by Django 4.0.6 on 2022-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_attachment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_gift',
        ),
        migrations.AddField(
            model_name='project',
            name='is_personal',
            field=models.BooleanField(default=False, verbose_name='Личный проект'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(verbose_name='ссылка'),
        ),
    ]
