# Generated by Django 4.0.6 on 2022-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_is_gift_project_is_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=2050, verbose_name='ссылка'),
        ),
    ]
