# Generated by Django 4.0.6 on 2022-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Есть ответы'),
        ),
    ]
