# Generated by Django 4.0.6 on 2022-08-16 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_comment_is_replied'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together={('account', 'object_id', 'content_type')},
        ),
    ]
