# Generated by Django 4.0.6 on 2022-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_likedislike_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_replied',
            field=models.BooleanField(default=False, editable=False, verbose_name='Есть ответы'),
        ),
    ]
